server.port=${PORT:8080}
spring.application.name=sentinel-api
spring.main.banner-mode=off
spring.main.allow-bean-definition-overriding=true
management.tracing.enabled=true
logging.level.com.ing.sentinel=INFO
logging.level.com.google.adk=WARN
